---
- name: Install ACM
  hosts: localhost
  vars:
    ocp_username: admin
    ocp_password: openshift
    ocp_api_url: https://api.hub.ocpdemo.labs:6443
  tasks:
    - name: Log in (obtain access token)
      community.okd.openshift_auth:
        username: "{{ ocp_username }}"
        password: "{{ ocp_password }}"
        host: "{{ ocp_api_url }}"
        verify_ssl: false
      register: openshift_auth_results

    - name: Create OCP Resources to prepare operator setup
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', item) }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        host: "{{ ocp_api_url }}"
        verify_ssl: false
        continue_on_error: true
      loop:
        - templates/01-acm/00-acm-project.yml
        - templates/01-acm/01-acm-operatorgroup.yml
        - templates/01-acm/02-acm-subscription.yml

    - name: Check Operator instantiation
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: open-cluster-management
        wait: true
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        host: "{{ ocp_api_url }}"
        verify_ssl: false
        label_selectors:
          - name=multiclusterhub-operator

    - name: Create OCP Resources to prepare operator setup
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('ansible.builtin.template', item) }}"
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        host: "{{ ocp_api_url }}"
        verify_ssl: false
      loop:
        - templates/01-acm/acm_multiclusterhub.yml
